import os
import psycopg2
from psycopg2 import Error
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

class DatabaseManager:
    """
    A class to manage all database connections and operations for the Hospital Management System.
    """

    def __init__(self):
        # Fetch database credentials from environment variables securely
        self.db_config = {
            "host": os.getenv("DB_HOST"),
            "database": os.getenv("DB_NAME"),
            "user": os.getenv("DB_USER"),
            "password": os.getenv("DB_PASSWORD"),
            "port": os.getenv("DB_PORT", "5432")
        }
        self.connection = None
        self.connect()

    def connect(self):
        """Establish a connection to the database."""
        try:
            # Ensure no essential connection variables are missing
            if not all([self.db_config["host"], self.db_config["password"]]):
                print("Error: Missing database credentials in .env file.")
                return

            self.connection = psycopg2.connect(**self.db_config)
            print("Database connection successfully established.")
        except Error as e:
            print(f"Error connecting to database: {e}")

    def disconnect(self):
        """Close the database connection safely."""
        if self.connection:
            self.connection.close()
            print("Database connection closed.")

    def execute_read_query(self, query, params=None):
        """
        Execute a SELECT query and return the fetched records along with column names.
        """
        if not self.connection or self.connection.closed:
            self.connect()
        
        # SAFETY CHECK: If connection failed, abort gracefully instead of crashing
        if not self.connection:
            print("Query execution aborted: No active database connection.")
            return None, None
        
        try:
            cursor = self.connection.cursor()
            cursor.execute(query, params)
            records = cursor.fetchall()
            column_names = [desc[0] for desc in cursor.description]
            cursor.close()
            return records, column_names
        except Error as e:
            print(f"Error executing read query: {e}")
            return None, None

    def execute_write_query(self, query, params=None):
        """
        Execute an INSERT, UPDATE, or DELETE query.
        """
        if not self.connection or self.connection.closed:
            self.connect()

        # SAFETY CHECK: If connection failed, abort gracefully instead of crashing
        if not self.connection:
            print("Transaction aborted: No active database connection.")
            return False

        try:
            cursor = self.connection.cursor()
            cursor.execute(query, params)
            self.connection.commit()
            cursor.close()
            return True
        except Error as e:
            print(f"Error executing write query: {e}")
            self.connection.rollback()
            return False

    # -------------------------------------------------------------------------
    # PATIENTS MODULE CRUD OPERATIONS
    # -------------------------------------------------------------------------

    def get_all_patients(self, search_term=None, filter_type="Name"):
        """Retrieve patients filtered strictly by either exact ID or partial Name."""
        if search_term:
            if filter_type == "ID":
                query = "SELECT * FROM PATIENTS WHERE Patient_ID::text = %s ORDER BY Patient_ID ASC;"
                return self.execute_read_query(query, (search_term,))
            else:
                query = "SELECT * FROM PATIENTS WHERE First_Name ILIKE %s OR Last_Name ILIKE %s ORDER BY Patient_ID ASC;"
                like_term = f"%{search_term}%"
                return self.execute_read_query(query, (like_term, like_term))
        query = "SELECT * FROM PATIENTS ORDER BY Patient_ID ASC;"
        return self.execute_read_query(query)

    def get_patient_by_id(self, patient_id):
        """Fetch a specific patient's details for the UPDATE screen."""
        query = "SELECT * FROM PATIENTS WHERE Patient_ID = %s;"
        return self.execute_read_query(query, (patient_id,))

    def add_new_patient(self, first_name, last_name, dob, phone, address):
        """Insert a new patient profile into the PATIENTS table. ID is auto-generated by the DB sequence."""
        query = """
            INSERT INTO PATIENTS (First_Name, Last_Name, Date_Of_Birth, Phone_Number, Address)
            VALUES (%s, %s, %s, %s, %s);
        """
        params = (first_name, last_name, dob, phone if phone else None, address if address else None)
        return self.execute_write_query(query, params)
    
    def update_patient_info(self, patient_id, first_name, last_name, phone, address):
        """Update basic information for a specific patient."""
        query = """
            UPDATE PATIENTS 
            SET First_Name = %s, Last_Name = %s, Phone_Number = %s, Address = %s 
            WHERE Patient_ID = %s;
        """
        params = (first_name, last_name, phone, address, patient_id)
        return self.execute_write_query(query, params)

    def delete_patient(self, patient_id):
        """Delete a patient record completely by their unique ID."""
        query = "DELETE FROM PATIENTS WHERE Patient_ID = %s;"
        return self.execute_write_query(query, (patient_id,))

    # -------------------------------------------------------------------------
    # STAFF & DEPARTMENTS CRUD OPERATIONS
    # -------------------------------------------------------------------------

    def get_all_departments(self):
        """Retrieve all records from DEPARTMENTS for UI dropdown configurations."""
        query = "SELECT Department_ID, Department_Name FROM DEPARTMENTS ORDER BY Department_Name ASC;"
        return self.execute_read_query(query)

    def get_staff_with_departments(self, search_term=None, filter_type="Name"):
        """Retrieve staff details filtered strictly by partial Name or partial Role."""
        base_query = """
            SELECT s.Employee_ID, s.First_Name, s.Last_Name, s.Role, d.Department_Name 
            FROM STAFF s
            JOIN DEPARTMENTS d ON s.Department_ID = d.Department_ID
        """
        if search_term:
            like_term = f"%{search_term}%"
            if filter_type == "Role":
                query = base_query + " WHERE s.Role ILIKE %s ORDER BY s.Employee_ID ASC;"
                return self.execute_read_query(query, (like_term,))
            else:
                query = base_query + " WHERE s.First_Name ILIKE %s OR s.Last_Name ILIKE %s ORDER BY s.Employee_ID ASC;"
                return self.execute_read_query(query, (like_term, like_term))
        query = base_query + " ORDER BY s.Employee_ID ASC;"
        return self.execute_read_query(query)

    def get_staff_by_id(self, employee_id):
        """Fetch basic staff properties by target ID."""
        query = "SELECT Employee_ID, First_Name, Last_Name, Role, Department_ID FROM STAFF WHERE Employee_ID = %s;"
        return self.execute_read_query(query, (employee_id,))

    def add_new_staff(self, first_name, last_name, role, department_id):
        """Insert a new staff record. Employee_ID auto-generates via sequence."""
        query = """
            INSERT INTO STAFF (First_Name, Last_Name, Role, Department_ID)
            VALUES (%s, %s, %s, %s);
        """
        params = (first_name, last_name, role, department_id)
        return self.execute_write_query(query, params)

    def update_staff_info(self, employee_id, first_name, last_name, role, department_id):
        """Modify staff details matching target identifiers."""
        query = """
            UPDATE STAFF 
            SET First_Name = %s, Last_Name = %s, Role = %s, Department_ID = %s 
            WHERE Employee_ID = %s;
        """
        params = (first_name, last_name, role, department_id, employee_id)
        return self.execute_write_query(query, params)

    def delete_staff(self, employee_id):
        """Safely drop targeted employee indexes matching unique keys."""
        query = "DELETE FROM STAFF WHERE Employee_ID = %s;"
        return self.execute_write_query(query, (employee_id,))

    # -------------------------------------------------------------------------
    # APPOINTMENTS & VISITS (STAGE D PROCEDURES / FUNCTIONS INTEGRATION)
    # -------------------------------------------------------------------------

    def get_detailed_appointments(self, search_term=None, filter_type="Patient Name"):
        """Retrieve appointments filtered by partial Patient Name or partial Staff Name."""
        base_query = """
            SELECT a.Appointment_ID, a.Appointment_Date, 
                   p.First_Name || ' ' || p.Last_Name AS Patient_Name, 
                   s.First_Name || ' ' || s.Last_Name AS Staff_Name, 
                   r.Room_Number, a.Status
            FROM APPOINTMENTS a
            JOIN PATIENTS p ON a.Patient_ID = p.Patient_ID
            JOIN STAFF s ON a.Employee_ID = s.Employee_ID
            JOIN ROOMS r ON a.Room_ID = r.Room_ID
        """
        if search_term:
            like_term = f"%{search_term}%"
            if filter_type == "Staff Name":
                query = base_query + " WHERE s.First_Name ILIKE %s OR s.Last_Name ILIKE %s ORDER BY a.Appointment_Date DESC;"
            else:
                query = base_query + " WHERE p.First_Name ILIKE %s OR p.Last_Name ILIKE %s ORDER BY a.Appointment_Date DESC;"
            return self.execute_read_query(query, (like_term, like_term))
        query = base_query + " ORDER BY a.Appointment_Date DESC;"
        return self.execute_read_query(query)

    def add_new_appointment(self, appointment_date, patient_id, employee_id, room_id):
        """Insert a new record into APPOINTMENTS. ID is generated by DB sequence."""
        query = """
            INSERT INTO APPOINTMENTS (Appointment_Date, Patient_ID, Employee_ID, Room_ID, Status)
            VALUES (%s, %s, %s, %s, 'Scheduled');
        """
        params = (appointment_date, patient_id, employee_id, room_id)
        return self.execute_write_query(query, params)

    def call_complete_appointment_procedure(self, appointment_id, patient_id, cost, diagnosis):
        """Invoke Stage D complete_appointment stored procedure safely."""
        if not self.connection or self.connection.closed:
            self.connect()
        if not self.connection:
            return False
        try:
            cursor = self.connection.cursor()
            cursor.execute("CALL complete_appointment(%s, %s, %s, %s);", 
                           (int(appointment_id), int(patient_id), float(cost), diagnosis))
            self.connection.commit()
            cursor.close()
            return True
        except Exception as e:
            print(f"Error executing complete_appointment procedure: {e}")
            self.connection.rollback()
            return False

    def call_get_patient_history_function(self, patient_id):
        """Invoke Stage D get_patient_history function and consume ref cursor."""
        if not self.connection or self.connection.closed:
            self.connect()
        if not self.connection:
            return None
        try:
            cursor = self.connection.cursor()
            cursor.callproc("get_patient_history", [int(patient_id)])
            ref_cursor_name = cursor.fetchone()[0]
            
            cursor.execute(f'FETCH ALL FROM "{ref_cursor_name}";')
            records = cursor.fetchall()
            
            cursor.close()
            return records
        except Exception as e:
            print(f"Error consuming get_patient_history ref cursor: {e}")
            self.connection.rollback()
            return None
        
        # -------------------------------------------------------------------------
    # PHARMACY & MEDICATIONS MODULE OPERATIONS
    # -------------------------------------------------------------------------

    def get_all_medications(self):
        """Retrieve all catalog medications ordered by name."""
        query = "SELECT Medication_ID, Medication_Name FROM MEDICATIONS ORDER BY Medication_Name ASC;"
        return self.execute_read_query(query)

    def get_medication_by_id(self, medication_id):
        """Fetch a specific medication item by ID."""
        query = "SELECT Medication_ID, Medication_Name FROM MEDICATIONS WHERE Medication_ID = %s;"
        return self.execute_read_query(query, (medication_id,))

    def add_new_medication(self, medication_name):
        """Insert a new drug item into the MEDICATIONS catalog."""
        query = "INSERT INTO MEDICATIONS (Medication_Name) VALUES (%s);"
        return self.execute_write_query(query, (medication_name,))

    def update_medication_info(self, medication_id, medication_name):
        """Modify a specific medication catalog name."""
        query = "UPDATE MEDICATIONS SET Medication_Name = %s WHERE Medication_ID = %s;"
        return self.execute_write_query(query, (medication_name, medication_id))

    def delete_medication(self, medication_id):
        """Safely drop a medication item from the formulary catalog index."""
        query = "DELETE FROM MEDICATIONS WHERE Medication_ID = %s;"
        return self.execute_write_query(query, (medication_id,))

    def get_detailed_prescriptions(self, search_term=None, filter_type="Patient Name"):
        """Retrieve prescriptions filtered by partial Patient Name or partial Medication Name."""
        base_query = """
            SELECT pr.Prescription_ID, pt.First_Name || ' ' || pt.Last_Name AS Patient_Name,
                   st.First_Name || ' ' || st.Last_Name AS Doctor_Name, md.Medication_Name, pr.Dosage
            FROM PRESCRIPTIONS pr
            JOIN VISITS v ON pr.Visit_ID = v.Visit_ID
            JOIN PATIENTS pt ON v.Patient_ID = pt.Patient_ID
            JOIN STAFF st ON v.Employee_ID = st.Employee_ID
            JOIN MEDICATIONS md ON pr.Medication_ID = md.Medication_ID
        """
        if search_term:
            like_term = f"%{search_term}%"
            if filter_type == "Medication":
                query = base_query + " WHERE md.Medication_Name ILIKE %s ORDER BY pr.Prescription_ID DESC;"
                return self.execute_read_query(query, (like_term,))
            else:
                query = base_query + " WHERE pt.First_Name ILIKE %s OR pt.Last_Name ILIKE %s ORDER BY pr.Prescription_ID DESC;"
                return self.execute_read_query(query, (like_term, like_term))
        query = base_query + " ORDER BY pr.Prescription_ID DESC;"
        return self.execute_read_query(query)

    def add_new_prescription(self, dosage, visit_id, medication_id):
        """Insert a new patient prescription. Prescription_ID is generated by DB sequence."""
        query = """
            INSERT INTO PRESCRIPTIONS (Dosage, Visit_ID, Medication_ID)
            VALUES (%s, %s, %s);
        """
        params = (dosage, visit_id, medication_id)
        return self.execute_write_query(query, params)
    
    # -------------------------------------------------------------------------
    # BILLING & INVOICES MODULE OPERATIONS
    # -------------------------------------------------------------------------

    def get_detailed_invoices(self, search_term=None, filter_type="Patient Name"):
        """Retrieve invoices filtered strictly by exact Invoice ID or partial Patient Name."""
        base_query = """
            SELECT i.Invoice_ID, p.First_Name || ' ' || p.Last_Name AS Patient_Name, i.Total_Amount, i.Billing_Date
            FROM INVOICES i
            JOIN PATIENTS p ON i.Patient_ID = p.Patient_ID
        """
        if search_term:
            if filter_type == "Invoice ID":
                query = base_query + " WHERE i.Invoice_ID::text = %s ORDER BY i.Invoice_ID DESC;"
                return self.execute_read_query(query, (search_term,))
            else:
                query = base_query + " WHERE p.First_Name ILIKE %s OR p.Last_Name ILIKE %s ORDER BY i.Invoice_ID DESC;"
                like_term = f"%{search_term}%"
                return self.execute_read_query(query, (like_term, like_term))
        query = base_query + " ORDER BY i.Invoice_ID DESC;"
        return self.execute_read_query(query)

    def add_new_invoice(self, total_amount, billing_date, patient_id):
        """Insert a new financial billing invoice. ID auto-generates via sequence."""
        query = """
            INSERT INTO INVOICES (Total_Amount, Billing_Date, Patient_ID)
            VALUES (%s, %s, %s);
        """
        params = (total_amount, billing_date, patient_id)
        return self.execute_write_query(query, params)

    def get_invoice_by_id(self, invoice_id):
        """Fetch basic structured properties matching a target Invoice ID constraint."""
        query = "SELECT Invoice_ID, Total_Amount, Billing_Date, Patient_ID FROM INVOICES WHERE Invoice_ID = %s;"
        return self.execute_read_query(query, (invoice_id,))

    def update_invoice_info(self, invoice_id, total_amount, billing_date, patient_id):
        """Modify tracking variables matching target billing identifiers."""
        query = """
            UPDATE INVOICES 
            SET Total_Amount = %s, Billing_Date = %s, Patient_ID = %s 
            WHERE Invoice_ID = %s;
        """
        params = (total_amount, billing_date, patient_id, invoice_id)
        return self.execute_write_query(query, params)

    def delete_invoice(self, invoice_id):
        """Safely drop targeting financial ledger records matching unique key constraints."""
        query = "DELETE FROM INVOICES WHERE Invoice_ID = %s;"
        return self.execute_write_query(query, (invoice_id,))
    
    # -------------------------------------------------------------------------
    # REPORTS MODULE OPERATIONS (STAGE B QUERIES & STAGE D EXECUTIONS)
    # -------------------------------------------------------------------------

    def run_report_patients_2024(self):
        """
        Execute Stage B Query 1 (EXISTS structure):
        Select patients who had hospital visits recorded in the year 2024.
        """
        query = """
            SELECT p.Patient_ID, p.First_Name, p.Last_Name, p.Phone_Number
            FROM PATIENTS p
            WHERE EXISTS (
                SELECT 1 FROM VISITS v 
                WHERE v.Patient_ID = p.Patient_ID 
                AND EXTRACT(YEAR FROM v.Visit_Date) = 2024
            );
        """
        return self.execute_read_query(query)

    def run_report_high_billing(self):
        """
        Execute Stage B Query 5 (Aggregated grouping constraints):
        Select patients whose total accumulated invoices value exceeds $1500.
        """
        query = """
            SELECT 
                p.Patient_ID, 
                p.First_Name || ' ' || p.Last_Name AS Patient_Name, 
                SUM(i.Total_Amount) AS Total_Billed_Amount
            FROM PATIENTS p
            JOIN INVOICES i ON p.Patient_ID = i.Patient_ID
            GROUP BY p.Patient_ID, p.First_Name, p.Last_Name
            HAVING SUM(i.Total_Amount) > 1500
            ORDER BY Total_Billed_Amount DESC;
        """
        return self.execute_read_query(query)

    def call_get_available_beds_function(self, department_id):
        """Invoke Stage D get_available_beds database function using standard execution windows."""
        if not self.connection or self.connection.closed:
            self.connect()
        if not self.connection:
            return None
        try:
            cursor = self.connection.cursor()
            cursor.execute("SELECT get_available_beds(%s);", (int(department_id),))
            result = cursor.fetchone()[0]
            cursor.close()
            return result
        except Exception as e:
            print(f"Error calling get_available_beds function: {e}")
            self.connection.rollback()
            return None

    def call_discharge_procedure(self, admission_id):
        """Invoke Stage D discharge_patient backend processing procedure block."""
        if not self.connection or self.connection.closed:
            self.connect()
        if not self.connection:
            return False
        try:
            cursor = self.connection.cursor()
            cursor.execute("CALL discharge_patient(%s);", (int(admission_id),))
            self.connection.commit()
            cursor.close()
            return True
        except Exception as e:
            print(f"Error calling discharge_patient procedure: {e}")
            self.connection.rollback()
            return False