insert into MEDICATIONS (Medication_ID, Medication_Name) values (1, 'Anagrelide Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (2, 'Lorazepam');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (3, 'DHC Camu Camu White Day Milk');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (4, 'Enoxaparin Sodium');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (5, 'Treatment Set TS343826');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (6, 'Plan B One-Step');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (7, 'Lansoprazole');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (8, 'Childrens Plus Cough and Runny Nose');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (9, 'simvastatin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (10, 'Air Pollution Detox');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (11, 'EQUALINE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (12, 'Cefprozil');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (13, 'Mylanta Gas');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (14, 'KIDS RELIEF CALENDULA');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (15, 'IOPE S.S. CONDITIONING COLOR BASE No.60');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (16, 'Laxative for Women');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (17, 'NicFix Plus');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (18, 'Fosinopril Sodium and Hydrochlorothiazide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (19, 'Alprazolam');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (20, 'Tonico-Heel');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (21, 'MEIJER LUBRICANT EYE DROPS');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (22, 'Oxygen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (23, 'Haloperidol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (24, 'Canary Grass');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (25, 'Chlorpromazine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (26, 'good sense nicotine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (27, 'Herbal UTAPLAS.TN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (28, 'Heparin Sodium');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (29, 'Viscum Belladonna');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (30, 'Lexapro');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (31, 'Hemorrhoidal');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (32, 'CLOMIPRAMINE HYDROCHLORIDE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (33, 'Doxycycline Hyclate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (34, 'Burr Oak');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (35, 'rx act nasal decongestant pe');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (36, 'Metoprolol Tartate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (37, 'ANTIBACTERIAL');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (38, 'Catapres');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (39, 'CAPTOPRIL');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (40, 'Oral Analgesic');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (41, 'Acetaminophen, Phenylephrine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (42, 'Torsemide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (43, 'Sore Throat Right Side');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (44, 'Metoprolol Tartrate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (45, 'CareOne Childrens Pain and Fever');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (46, 'Disney PIXAR Cars Antibacterial Hand Wipes');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (47, 'Red Alder');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (48, 'Lamotrigine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (49, 'Decolorized Iodine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (50, 'Simvastatin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (51, 'Sulfamethoxazole and Trimethoprim');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (52, 'Lisinopril and HCTZ');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (53, 'Droperidol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (54, 'Venlafaxine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (55, 'up and up miconazole 1');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (56, 'Sertraline Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (57, 'RENEWAL');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (58, 'Nitroglycerin Transdermal System');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (59, 'Ampicillin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (60, 'Topiramate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (61, 'Clonazepam');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (62, 'Sertraline Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (63, 'ACER RUBRUM POLLEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (64, 'CENTER-AL - AVENA SATIVA POLLEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (65, 'Ciprofloxacin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (66, 'Pravastatin Sodium');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (67, 'Duloxetine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (68, 'Tinnitus');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (69, 'Risperidone');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (70, 'Dopamine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (71, 'EQUATE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (72, 'Trixaicin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (73, 'Nicardipine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (74, 'PRO-RED');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (75, 'Lym D');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (76, 'UNIQUE NATURAL PREMIUM SHEA BUTTER');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (77, 'Tobramycin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (78, 'American Infection Control Antiseptic Hand Wipes');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (79, 'Enalapril Maleate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (80, 'Infla');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (81, 'BencoCaine Topical Anesthetic');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (82, 'Kalium aceticum comp. 6');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (83, 'Cephalexin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (84, 'Auvi-Q');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (85, 'A and D Original');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (86, 'Mulberry');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (87, 'Tusnel');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (88, 'FML');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (89, 'BusPIRone Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (90, 'PDI Sani-Hands');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (91, 'Mirtazapine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (92, 'Amitriptyline Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (93, 'Guaifenesin and Codeine Phosphate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (94, 'Oregon Ash');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (95, 'Animal Allergens, AP Horse Hair and Dander');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (96, 'Hormeel');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (97, 'Molds, Rusts and Smuts, Hormodendrum cladosporioides');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (98, 'Symmetry Hand Sanitizer');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (99, 'Lubriderm Daily Moisture');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (100, 'Breakout Clearing Emergency Spot Fix');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (101, 'R2');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (102, 'Topcare Tussin DM');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (103, 'LISINOPRIL AND HYDROCHLOROTHIAZIDE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (104, 'Progena');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (105, 'Diltiazem Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (106, 'ATORVASTATIN CALCIUM');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (107, 'Onfi');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (108, 'GEMCITABINE HYDROCHLORIDE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (109, 'Oregano');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (110, 'care one ibuprofen cold and sinus');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (111, 'Creomulsion');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (112, 'CANIS LUPUS FAMILIARIS SKIN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (113, 'Di-Dak-Sol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (114, 'Viagra');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (115, 'Hyoscyamine Sulfate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (116, 'DEMEROL');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (117, 'GABAPENTIN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (118, 'Rozerem');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (119, '4 Kids Complete Cold and Flu');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (120, 'Pomegranate Rose Hand Sanitizer');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (121, 'Therapeutic');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (122, 'Cefpodoxime Proxetil');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (123, 'Renes Mesenchyme');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (124, 'K-Vescent');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (125, 'Oxygen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (126, 'Levitra');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (127, 'COLGATE 2IN1');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (128, 'Atenolol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (129, 'Norco');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (130, 'Umcka Cold Flu Berry');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (131, 'Pleo Nig');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (132, 'IVA ANNUA VAR ANNUA POLLEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (133, 'Atenolol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (134, 'Vagisil Anti Itch Maximum Strength');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (135, 'Cataract Crystalline Lens');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (136, 'Esmolol Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (137, 'ANASTROZOLE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (138, 'Broncotron');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (139, 'Eron Healing Tonic');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (140, 'Atomoxetine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (141, 'Secret Antiperspirant');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (142, 'Oxygen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (143, 'Good Neighbor Pharmacy ibuprofen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (144, 'Cefpodoxime Proxetil');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (145, 'Non-Drowsy Sinus Congestion and Pain');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (146, 'Dicyclomine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (147, 'Nasal Guard');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (148, 'Ibuprofen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (149, 'Lotrel');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (150, 'Zenzedi');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (151, 'Rectiv');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (152, 'Ibuprofen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (153, 'Bladder Kidney');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (154, 'Sinus Congestion and Pain Daytime Nighttime');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (155, 'Nicorette');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (156, 'A AND A Diaper Rash cream');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (157, 'Amlodipine Besylate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (158, 'Ranitidine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (159, 'Crest Pro-Health Stages');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (160, 'MORUS ALBA POLLEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (161, 'Calcium Disodium Versenate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (162, 'Dog Fennel');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (163, 'NITROGEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (164, 'Amlodipine Besylate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (165, 'Helium');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (166, 'Hydrocodone Bitartrate and Acetaminophen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (167, 'Molds, Rusts and Smuts, Alternaria tenuis');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (168, 'Aminosyn');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (169, 'Tussi Pres');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (170, 'Fluocinonide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (171, 'Lemon Verbena Antibacterial Hand Wash');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (172, 'Prochlorperazine Maleate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (173, 'Motion sickness');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (174, 'Neutrogena Oil Free Acne Wash');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (175, 'Felbamate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (176, 'BOBBI BROWN EXTRA');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (177, 'Solar Protection Formula SPF 60 Tinted Concealer - (Honey)');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (178, 'Carbidopa and Levodopa');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (179, 'Advanced Hand Sanitizer');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (180, 'Nighttime Sleep-aid');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (181, 'Pollens - Weeds, Marshelder/Poverty Mix');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (182, 'PAROXETINE HYDROCHLORIDE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (183, 'APIS MELLIFICA');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (184, 'DayQuil Severe');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (185, 'Apis Regina Cerebri');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (186, 'OxyContin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (187, 'TRAMADOL HYDROCHLORIDE AND ACETAMINOPHEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (188, 'Arroyo Willow');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (189, 'Vagi-Clear');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (190, 'HEPAR SULPH. CALC.');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (191, 'Childrens Allergy Relief');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (192, 'Carbidopa and Levodopa');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (193, 'Zolpidem Tartrate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (194, 'DOXEPIN HYDROCHLORIDE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (195, 'Kiehls Since 1851 Facial Fuel UV Guard Broad Spectrum SPF 50 Plus Sunscreen WR80');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (196, 'Risperidone');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (197, 'ESTRADIOL VALERATE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (198, 'SyImmune');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (199, 'Triple Antibiotic Plus');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (200, 'Torsemide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (201, 'Fluoxetine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (202, 'Duloxetine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (203, 'Olanzapine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (204, 'Hazelnut');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (205, 'Sensodyne Complete Protection');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (206, 'Navy Bean');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (207, 'gent-L-tip');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (208, 'TRICHODERMA LIGNORUM');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (209, 'Bromocriptine mesylate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (210, '3 CONCEPT EYES HONEY FACE CHIFFON FLUID 001');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (211, 'Pecan Pollen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (212, 'Glipizide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (213, 'Optiray');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (214, 'Prochlorperazine Maleate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (215, 'STANDARDIZED BERMUDA GRASS POLLEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (216, 'Namenda');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (217, 'Donald Duck Sun Smacker SPF 24 Tropical Touchdown');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (218, 'CARE ONE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (219, 'St. Ives');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (220, 'Hydromorphone Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (221, 'SHISEIDO WHITE LUCENT');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (222, 'cyclobenzaprine hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (223, 'Sertraline Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (224, 'Levetiracetam');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (225, 'Decolorized Iodine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (226, 'Oxygen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (227, 'Plantain Beeswax Cough Relief');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (228, 'Gabapentin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (229, 'Aspirin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (230, 'Trace Elements 4');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (231, 'NARS');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (232, 'Estropipate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (233, 'Articulatio Coxae 8');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (234, 'VANATAB DX');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (235, 'healthy accents antacid');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (236, 'Lorazepam');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (237, 'Anticoagulant Citrate Dextrose A');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (238, 'Fluoxetine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (239, 'Plegridy');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (240, 'Hydrocortisone Butyrate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (241, 'Grass Smut Mixture');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (242, 'Manefit Beauty Planner Lily Whitening Eye Patch');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (243, 'Impact Fix Pure Essence Foundation');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (244, 'Venlafaxine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (245, 'Trandolapril');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (246, 'SOUR DOCK SHEEP SORREL POLLEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (247, 'Trazodone Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (248, 'Type 4 Noise Regular');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (249, 'Male Stimulant');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (250, 'Opana');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (251, 'Right Guard Sport');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (252, 'Bisoprolol Fumarate and Hydrochlorothiazide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (253, 'Metformin hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (254, 'Famotidine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (255, 'Nasal');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (256, 'Terconazole');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (257, 'DR. RECKEWEG R55 Rutavine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (258, 'MEDI-FIRST Ibuprofen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (259, 'Clozapine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (260, 'Pollens - Weeds and Garden Plants, Plantain, English Plantago lanceolata');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (261, 'Sterile Water');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (262, 'Evista');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (263, 'Nabumetone');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (264, 'Niphanoid');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (265, 'LAMICTAL');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (266, 'INDOMETHACIN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (267, 'Black Willow');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (268, 'Allopurinol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (269, 'Stool Softener');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (270, 'Telmisartan');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (271, 'Nifedipine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (272, 'PAIN RELIEVING PATCH ULTRA STRENGTH');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (273, 'Fosphenytoin Sodium');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (274, 'RESILIENCE LIFT EXTREME CREME COMPACT MAKEUP');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (275, 'Promethazine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (276, 'Cephalexin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (277, 'MEDICAGO SATIVA POLLEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (278, 'Naproxen Sodium');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (279, 'Bacti-Stat AE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (280, 'FNG');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (281, 'Vicks Sinex');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (282, 'Multi Vitamin and Fluoride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (283, 'Galantamine Hydrobromide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (284, 'OMNIPRED');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (285, 'Fluphenazine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (286, 'Sodium Polystyrene Sulfonate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (287, 'Rayito de Sol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (288, 'Flurbiprofen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (289, 'Miss Spa');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (290, 'Rhubarb');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (291, 'Magnesite Viscum');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (292, 'AZITHROMYCIN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (293, 'SINUS PAIN AND CONGESTION');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (294, 'SNAIL THERAPY 50 BB');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (295, 'Ready Foundation');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (296, 'Potassium Chloride in Sodium Chloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (297, 'METRONIDAZOLE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (298, 'Diclofenac Sodium');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (299, 'XtraCare 2 in 1 Hair Cleanse and Condition');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (300, 'Lovenox');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (301, 'SAGE FOOD');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (302, 'Synthroid');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (303, 'Piperacillin and Tazobactam');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (304, 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (305, 'ARALIA QUINQUEFOLIA');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (306, 'Benazepril Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (307, 'Aspergillus fumigatus');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (308, '4 in 1 Pressed Mineral SPF 15 Light');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (309, 'White Poplar');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (310, 'Hectorol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (311, 'levomefolate calcium, pyridoxal 5-phosphate, methylcobalamin and schizochytrium dha oil');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (312, 'Dr G deWrinkle BOOSTER ample by EGF');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (313, 'Reguloid');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (314, 'Neoral');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (315, 'Severe Cold and Congestion Maximum Strength');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (316, 'Medicated Pain Relief');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (317, 'Circulation Complex');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (318, 'Habitrol Patch');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (319, 'profen ib');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (320, 'Torsemide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (321, 'Good Sense Nasal');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (322, 'levalbuterol hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (323, 'Doxycycline Hyclate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (324, 'Fosinopril sodium');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (325, 'Vinblastine Sulfate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (326, 'NEXIUM');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (327, 'Methotrexate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (328, 'NiteTime Severe Cold and Flu');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (329, 'Antizol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (330, 'METOPROLOL SUCCINATE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (331, 'Ipratropium Bromide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (332, 'Metformin hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (333, 'Potassium Chloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (334, 'PEGINTRON');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (335, 'Isopropyl Alcohol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (336, 'Pomalyst');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (337, 'VITALUMIERE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (338, 'ESTRACE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (339, 'Berberis Populus');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (340, 'Whole Care');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (341, 'Intestaforce');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (342, 'HAND AND NATURE SANITIZER');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (343, 'Glycine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (344, 'Oxygen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (345, 'Torsemide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (346, 'Testred');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (347, 'CD DiorSkin Forever Flawless Perfection Fusion Wear Makeup SPF 25 - 023');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (348, 'Remedy Skin Repair');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (349, 'Bupropion Hydrocloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (350, 'Novarnica');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (351, 'Loratadine and Pseudoephedrine Sulfate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (352, 'Sprix');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (353, 'Betula Argentum');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (354, 'Diltiazem Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (355, 'CD DIORSKIN NUDE SKIN-GLOWING MAKEUP SUNSCREEN BROAD SPECTRUM SPF 15 031 Sand');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (356, 'Metformin Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (357, 'ESIKA');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (358, 'Sulfamethoxazole and Trimethoprim');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (359, 'Sore Throat');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (360, 'MEFOXIN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (361, 'Cold Remedy');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (362, 'YS Solution Ac Care');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (363, '4 in 1 Pressed Mineral SPF 15 Golden Dark');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (364, 'Lovastatin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (365, 'Potassium Chloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (366, 'Creamy Petroleum Jelly');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (367, 'IOPE SUPER VITAL');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (368, 'Cardizem LA');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (369, 'Molds, Rusts and Smuts, Fusarium vasinfectum');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (370, 'TopiCool Pain Relief');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (371, 'Viscum Salicis');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (372, 'lisinopril');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (373, 'Cyclobenzaprine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (374, 'Gelato APF');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (375, 'Treatment Set TS347116');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (376, 'Prograf');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (377, 'Premier Value Adult Glycerin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (378, 'Nitrous Oxide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (379, 'DEFENDER Foaming Hand Sanitizer');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (380, 'Isoniazid');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (381, 'ZOCOR');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (382, 'Children Acetaminophen Grape Flavored Chewable');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (383, 'Diltiazem Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (384, 'Sertraline');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (385, 'Condylox');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (386, 'Ocudox');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (387, 'Duloxetine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (388, 'HAEMONETICS 0.9 % Sodium Chloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (389, 'Fluconazole');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (390, 'Helium Oxygen Mix 70/30');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (391, 'NAPROXEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (392, 'Atenolol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (393, 'acid reducer');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (394, 'WESTERN FAMILY DIAPER RASH');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (395, 'GEMCITABINE HYDROCHLORIDE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (396, 'Tizanidine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (397, 'Acyclovir');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (398, 'Safe Harbor - Natural Sunscreen - Baby and Kids SPF50 Broad Spectrum Sunscreen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (399, 'Ovaplex');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (400, 'Red Mulberry');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (401, 'Antiseptic');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (402, 'Athomer');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (403, 'lovastatin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (404, 'Cidofovir');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (405, 'Baclofen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (406, 'Gabapentin');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (407, 'VALACYCLOVIR HYDROCHLORIDE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (408, 'COUMADIN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (409, 'Olanzapine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (410, 'Tough Guy Hand Sanitizer Wipes');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (411, 'nighttime cold and flu relief');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (412, 'EXCEDRIN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (413, 'Severe Cold and Flu');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (414, 'ENTOCORT');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (415, 'Topiramate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (416, 'KIDNEY DRAINAGE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (417, 'Cortisonum 30 Special Order');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (418, 'Oxygen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (419, 'Sure Original Solid Powder');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (420, 'REPAIRWEAR UPLIFTING FIRMING');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (421, 'AMOREPACIFIC FUTURE RESPONSE AGE DEFENSE DUAL EYE WITH SPF 25 SUNSCREEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (422, 'wal tussin cf');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (423, 'Hydralazine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (424, 'healthy accents clear lax');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (425, 'SERTRALINE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (426, 'Clonazepam');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (427, 'CLARINS Broad Spectrum SPF 15 Sunscreen Extra-Firming Foundation Tint 113');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (428, 'Dobutamine Hydrochloride in Dextrose');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (429, 'AMITRIPTYLINE HYDROCHLORIDE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (430, 'MAKESENSE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (431, 'Povidone Iodine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (432, 'Naproxen Sodium');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (433, '4 Way');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (434, 'Fairly Medium Foundation SPF 15');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (435, 'Junior Pain Relief');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (436, 'ADVAIR');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (437, 'SHISEIDO URBAN ENVIRONMENT');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (438, 'OXYGEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (439, 'triamcinolone acetonide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (440, 'BabyGanics Alcohol Free Foaming Hand Sanitizer');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (441, 'Methimazole');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (442, 'Pistachio');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (443, 'Benazepril Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (444, 'Hydroxyzine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (445, 'bronze-n-brighten');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (446, 'Hydrocodone Bitartrate And Acetaminophen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (447, 'verapamil hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (448, 'Haloperidol Decanoate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (449, 'Labetalol Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (450, 'Vitamin A D');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (451, 'Ciclopirox Olamine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (452, 'Allergena');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (453, 'ANTIMONIUM TART');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (454, 'healthy accents day time night time');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (455, 'Omeprazole');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (456, 'Meloxicam');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (457, 'HEALTHY HANDS PINK ANTIBACTERIAL HAND CLEANER');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (458, 'PROVENCE TWO WAY PACT');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (459, 'Dove DermaSeries');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (460, 'Corn Grass');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (461, 'Lortab 10/325');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (462, 'Bupropion hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (463, 'Mirtazapine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (464, 'Oxygen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (465, 'TRAMADOL HYDROCHLORIDE AND ACETAMINOPHEN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (466, 'Humco Sodium Bicarbonate');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (467, 'Secret Scent Expressions');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (468, 'Penicillium notatum');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (469, 'stop smoking aid');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (470, 'Black Cottonwood Pollen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (471, 'Lamotrigine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (472, 'McKesson Antimicrobial Hand');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (473, 'Sulfur 6 Special Order');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (474, 'CHERRY');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (475, 'Diclofenac Sodium');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (476, 'Lisinopril');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (477, 'Irbesartan and Hydrochlorothiazide');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (478, 'Artists Touch BB 01 Light');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (479, 'AMOXICILLIN');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (480, 'Acetaldehyde');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (481, 'Ibuprofen');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (482, 'Thyro-Chord');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (483, 'Artificial Tears Lubricant Eye');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (484, 'Risperidone');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (485, 'Red Kidney Beans');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (486, 'NUJEVI ACNE');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (487, 'ENTOCORT');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (488, 'triple antibiotic');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (489, 'CHAMOMILLA');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (490, 'Clomipramine Hydrochloride');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (491, 'NO-AD SPF4 Dark Tanning Oil');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (492, 'Diltiazem Hydrochloride Extended Release');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (493, 'Anti-Diarrheal');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (494, 'Carbocaine');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (495, 'Jurlique Sun Sunscreen SPF 30');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (496, 'Lady Speed Stick');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (497, 'MoodBrite');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (498, 'Nadolol');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (499, 'Terazol 3');
insert into MEDICATIONS (Medication_ID, Medication_Name) values (500, 'Orphenadrine Citrate');
